services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
    - DB_HOST=${DB_HOST}
    - DB_NAME=${DB_NAME}
    - DB_PASS=${DB_PASS}
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    env_file:
      - .env
    entrypoint:
    - sleep
    - infinity
    # image: docker/dev-environments-default:stable-1
    init: true
    ports:
    - "80:8080"
    - target: 80
      published: 8080
      protocol: tcp
      mode: host
    volumes:
      - ./:/api

  db:
    image: postgres:latest
    restart: always
    environment:
    - DB_HOST=${DB_HOST}
    - DB_NAME=${DB_NAME}
    - DB_PASS=${DB_PASS}
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASS}
    - POSTGRES_USER=${DB_USER}
    env_file:
      - .env
