services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: api
    volumes:
    - ./:/api
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
    command: "uvicorn api.server:app --port 8080 --reload --log-level info"
    env_file:
      - .env
    depends_on:
      - "db"
    ports:
      - "80:8080"
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    profiles: ["dev"]

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles: ["dev"]

volumes:
  db-data: